spring.application.name=pizzeria

# Chemin du fichier de log
logging.file.name=logs/app.log

# Taille max avant rotation
logging.logback.rollingpolicy.max-file-size=10MB

# Nombre de fichiers archivés conservés
logging.logback.rollingpolicy.max-history=30

# Niveau de log (optionnel)
logging.level.root=INFO
logging.level.com.tonpackage=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/pizzeria
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true